// This file was auto-generated by ML.NET Model Builder. 

using System;
using TestMLML.Model;

namespace TestMLML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Строка с сообщением
            var inputStr = string.Empty;
            // Счетчик
            int k = 1;
            Console.WriteLine("Write 'exit' to complete the work");
            while (k == 1)
            {
                Console.WriteLine("Read SMS");
                inputStr = Console.ReadLine();
                if (inputStr == "exit")
                {
                    k = 0;
                }
                else
                {
                    // Create single instance of sample data from first line of dataset for model input
                    ModelInput sampleData = new ModelInput()
                    {
                        Message = inputStr //@"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
                    };
                    var predictionResult = ConsumeModel.Predict(sampleData);
                    //Console.WriteLine("Using model to make single prediction -- Comparing actual Spam with predicted Spam from sample data...\n\n");
                    Console.WriteLine($"\nMessage: {sampleData.Message}");
                    Console.WriteLine($"Predicted Spam value {predictionResult.Prediction} \nPredicted Spam scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                    /*Console.WriteLine("=============== End of process, hit any key to finish ===============");
                    Console.ReadKey();*/
                }
            }
        }

    }
}
